name: EventMining
version: '1.0-SNAPSHOT'
main: de.dergamer09.eventMining.EventMining
api-version: '1.20'

commands:
  event:
    description: Hauptbefehl für das Mining Event
    usage: /event <pos1|pos2|top10>
    permission: event.use